# Generated by Django 3.2.9 on 2021-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_surname_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('age', models.CharField(max_length=32)),
                ('animal_id', models.IntegerField()),
            ],
        ),
    ]
