# Generated by Django 3.2.9 on 2021-11-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('adress1', models.CharField(max_length=32)),
                ('adress2', models.CharField(max_length=32)),
                ('town', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('userlevel', models.IntegerField()),
                ('passchange', models.BooleanField()),
                ('randomid', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('ip', models.CharField(max_length=32)),
                ('lasttry', models.DateTimeField()),
                ('trynumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('owner', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('fullid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('owner', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('paid', models.BooleanField()),
                ('intent_id', models.CharField(max_length=32)),
                ('fullid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ip', models.CharField(max_length=32)),
                ('lasttry', models.DateTimeField()),
                ('trynumber', models.IntegerField()),
                ('sender_name', models.CharField(max_length=64)),
                ('sender_mail', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=32)),
                ('longname', models.CharField(max_length=128)),
                ('shortname', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('private', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
