# Generated by Django 3.2.9 on 2021-11-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211112_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='surname',
            new_name='lastname',
        ),
    ]
