# Generated by Django 3.2.9 on 2021-11-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_surname_client_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
