# Generated by Django 3.2.9 on 2021-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211113_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.CharField(max_length=16),
        ),
    ]
