# Generated by Django 3.2.9 on 2021-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211113_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(),
        ),
    ]
